/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButtons: typeof import('./src/components/ActionButtons.vue')['default']
    AddAttachment: typeof import('./src/components/AddAttachment.vue')['default']
    AddProject: typeof import('./src/components/AddProject.vue')['default']
    Attachments: typeof import('./src/components/Attachments.vue')['default']
    Comments: typeof import('./src/components/Comments.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
