<template>
  <router-view />
</template>

<script lang="ts" setup>
  //
</script>
<style>

.hidden {
  opacity: 0;
  visibility: hidden;
  pointer-events: none;
}

.slide-bottom {
	        animation: slide-bottom 0.3s cubic-bezier(0.550, 0.085, 0.680, 0.530)  both;
}
.slide-top {
	        animation: slide-top 0.3s cubic-bezier(0.550, 0.085, 0.680, 0.530)  both;
}

.bounce-in-top {
	animation: bounce-in-top 1.1s both;
}

.tracking-in-expand {
	animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-1-28 11:26:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes slide-top {
  0% {
            transform: translateY(-100px);
  }
  100% {
            transform: translateY(0);
  }
}

@keyframes slide-bottom {
  0% {
            transform: translateY(0);
  }
  100% {
            transform: translateY(100px);
  }
}

 @keyframes bounce-in-top {
  0% {
    transform: translateY(-500px);
    animation-timing-function: ease-in;
    opacity: 0;
  }
  38% {
    transform: translateY(0);
    animation-timing-function: ease-out;
    opacity: 1;
  }
  55% {
    transform: translateY(-65px);
    animation-timing-function: ease-in;
  }
  72% {
    transform: translateY(0);
    animation-timing-function: ease-out;
  }
  81% {
    transform: translateY(-28px);
    animation-timing-function: ease-in;
  }
  90% {
    transform: translateY(0);
    animation-timing-function: ease-out;
  }
  95% {
    transform: translateY(-8px);
    animation-timing-function: ease-in;
  }
  100% {
    transform: translateY(0);
    animation-timing-function: ease-out;
  }
}

 @keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}


</style>